import Link from "next/link";
import { Camera, CheckCircle2, Images, MonitorPlay, QrCode, Users } from "lucide-react";
import { getMedia, getStudent } from "@/lib/data";

export default async function StudentHub({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const student = getStudent(id);
  if (!student) return <main className="grid min-h-dvh place-items-center bg-paper p-6"><div className="rule bg-paper p-8 text-center drop-2"><h1 className="headline text-3xl text-ink">PASS NOT FOUND</h1><p className="mt-3 text-ink-3">Ask the event desk for a new QR pass.</p></div></main>;
  const photos = getMedia().filter((m) => m.title === student.name).slice(0, 8);
  return <main className="grain min-h-dvh bg-paper px-4 py-5 sm:px-6 sm:py-8"><div className="mx-auto max-w-3xl">
    <header className="flex items-center justify-between rule-b pb-4"><div className="flex items-center gap-2"><span className="grid h-9 w-9 place-items-center bg-pop text-white"><QrCode className="h-5 w-5" /></span><span className="headline text-xl text-ink">LAUREATE <span className="text-pop">2K26</span></span></div><span className="stencil text-[9px] text-ink-3">STUDENT HUB</span></header>
    <section className="mt-7 bg-[rgb(var(--ink))] p-5 text-[rgb(var(--paper))] rule-thick drop-3 sm:p-8"><p className="stencil text-[9px] text-pop">WELCOME, GRADUATE</p><h1 className="headline mt-3 text-[clamp(2.5rem,10vw,5.5rem)]">{student.name}</h1><p className="mt-3 font-mono text-sm text-[rgb(var(--paper))]/60">{student.regNo} / {student.deptName}</p><div className="mt-7 grid gap-2 sm:grid-cols-3"><Link href="#stream" className="flex items-center gap-2 rule border-[rgb(var(--paper))]/30 bg-[rgb(var(--paper))]/10 px-3 py-3 text-sm font-bold"><MonitorPlay className="h-4 w-4 text-ok" /> LIVE STREAM</Link><Link href="#photos" className="flex items-center gap-2 rule border-[rgb(var(--paper))]/30 bg-[rgb(var(--paper))]/10 px-3 py-3 text-sm font-bold"><Images className="h-4 w-4 text-warn" /> MY PHOTOS</Link><Link href="#queue" className="flex items-center gap-2 rule border-[rgb(var(--paper))]/30 bg-[rgb(var(--paper))]/10 px-3 py-3 text-sm font-bold"><Camera className="h-4 w-4 text-pop" /> BOOTH QUEUE</Link></div></section>
    <section id="stream" className="mt-5 rule bg-paper drop-2"><div className="flex items-center justify-between rule-b bg-pop px-4 py-3 text-white"><span className="stencil text-[10px]">LIVE CEREMONY STREAM</span><span className="stencil flex items-center gap-1.5 text-[9px]"><span className="h-2 w-2 animate-blink bg-white" /> LIVE</span></div><div className="grid min-h-48 place-items-center bg-ink-black p-6 text-center"><MonitorPlay className="h-10 w-10 text-pop" /><p className="headline mt-3 text-2xl text-white">STREAM STARTING / LIVE NOW</p><p className="mt-2 text-xs text-white/50">The official ceremony stream will appear here.</p></div></section>
    <section id="queue" className="mt-5 grid gap-3 sm:grid-cols-2"><div className="rule bg-ok p-4 text-ink-black drop-2"><Users className="h-6 w-6" /><p className="stencil mt-4 text-[10px]">PHOTO BOOTH STATUS</p><p className="figure mt-2 text-4xl">{student.boothDone ? "COMPLETE" : "QUEUE READY"}</p><p className="mt-2 text-xs">Show this QR at the booth. The team will scan it and call your token.</p></div><div className="rule bg-paper-2 p-4 drop-2"><p className="stencil text-[10px] text-ink-3">YOUR CEREMONY JOURNEY</p>{[[student.attendance,"Registration"],[student.stageDone,"Stage photographs"],[student.boothDone,"Photo booth"],[student.certificateDone,"Certificate"]].map(([done,label]) => <div key={String(label)} className="mt-3 flex items-center gap-2 text-sm"><CheckCircle2 className={`h-4 w-4 ${done ? "text-ok" : "text-ink-3"}`} /><span className={done ? "font-bold text-ink" : "text-ink-3"}>{label}</span></div>)}</div></section>
    <section id="photos" className="mt-5 rule bg-paper p-4 drop-2"><div className="flex items-center justify-between"><div><p className="stencil text-[10px] text-pop">ALL YOUR PHOTOS</p><h2 className="headline mt-2 text-3xl text-ink">THE ARCHIVE</h2></div><span className="figure text-3xl text-ink">{photos.length}</span></div><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4">{photos.length ? photos.map((photo) => <div key={photo.id} className="grid aspect-square place-items-center rule bg-pop p-2 text-center text-white"><Images className="h-6 w-6" /><span className="mt-2 text-[10px] font-bold">{photo.category}</span></div>) : <p className="col-span-full bg-paper-2 p-8 text-center text-sm text-ink-3">Photos will appear here after your booth session is synced.</p>}</div></section>
    <p className="mt-6 text-center text-[11px] text-ink-3">Need help? Visit the registration desk and show this pass.</p>
  </div></main>;
}
